version: '3'

services:
  streamlit:
    build:
      context: .
    container_name: streamlit
    working_dir: '/src'
    tty: true
    env_file:
      - .env
    volumes:
      - ./src:/src
    ports:
      - '8501:8501'
    command: streamlit run app.py